---
title: "Bank"
format: html
editor: visual
---

```{r warning=FALSE, echo=FALSE, message=FALSE}
library(tidyverse)
library(readr)
library(stargazer)
library(ggcorrplot)
library(rstatix)
library(rpart)
library(ROSE)
library(tidymodels)
library(randomForest)
library(doParallel)
library(rio)
library(themis)
```

```{r message=FALSE, echo=FALSE}
Dataframe_base <- read_csv2("bank-full.csv")
head(Dataframe_base)

Dataframe <- Dataframe_base

# rozmiar ramki danych
dim(Dataframe)

# streszczenie danych numerycznych
Dataframe_numeric <- Dataframe[sapply(Dataframe, class) != "character"]
summary(Dataframe_numeric)


```

```{r echo=FALSE}
# Sprawdzenie czy występują braki danych 
colSums(is.na(Dataframe))

table(Dataframe$poutcome)

Dataframe$poutcome <- replace(Dataframe$poutcome, Dataframe$poutcome=="unknown", "no")


table(Dataframe$contact)
table(Dataframe$job)
table(Dataframe$education)



# zamiana "unknown" na NA 
Dataframe$contact <- replace(Dataframe$contact, Dataframe$contact=="unknown", NA)
Dataframe$education <- replace(Dataframe$education, Dataframe$education=="unknown", NA)
Dataframe$job <- replace(Dataframe$job, Dataframe$job=="unknown", NA)

colSums(is.na(Dataframe))

Dataframe <- na.omit(Dataframe)
```

```{r echo=FALSE}
# dystrbucja wieku
Dataframe |>  
  ggplot(aes(x = age))+geom_histogram(bins = 78)
  
```

```{r echo=FALSE}
# macierz korelacji
corr <- cor_mat(Dataframe_numeric)
p_mat <- cor_pmat(Dataframe_numeric)
ggcorrplot(corr, p.mat = p_mat,lab = T)
```

```{r message=FALSE, echo=FALSE}
# zamiana zmiennych typu character na numeric

Dataframe$marital <- match(Dataframe$marital, c("single", "married", "divorced"))
Dataframe$housing <- ifelse(Dataframe$housing == "yes", 1, 0)
Dataframe$loan <- ifelse(Dataframe$loan == "yes", 1, 0)
Dataframe$default <- ifelse(Dataframe$default == "yes", 1, 0)
Dataframe$job <- match(Dataframe$job, unique(Dataframe$job))
Dataframe$education <- match(Dataframe$education, unique(Dataframe$education))
Dataframe$month <- match(Dataframe$month, tolower(month.abb))
Dataframe$contact <- match(Dataframe$contact, unique(Dataframe$contact))
Dataframe$poutcome <- match(Dataframe$poutcome, unique(Dataframe$poutcome))
Dataframe$y <- ifelse(Dataframe$y == "yes", 1, 0)

Dataframe$y <- as.factor(Dataframe$y)

saveRDS(Dataframe, "Dane_czyste.rds")

```

```{r echo=FALSE}
# zliczenie obserwacji
plyr::count(Dataframe, "y")


ggplot(Dataframe, aes(x=y))+
  geom_bar(fill = "lightgreen")+
  xlab("no / yes")+
  theme_bw()

```

podział danych

```{r echo=FALSE}
set.seed(2000)

#podział danych na zbiór testowy i treingowy
data_split <- initial_split(Dataframe, 0.85)
train <- training(data_split)
test <- testing(data_split)



# walidacja krzyżowa
folds <- vfold_cv(train, v = 10)
keep_pred <- control_resamples(save_pred = TRUE, save_workflow = TRUE)

```

random forest

```{r echo=FALSE}
#przepis
rec <- recipe(y ~ ., data = train) |> 
  step_smote(y)


#model
RF <- rand_forest(mode = "classification",
                  engine = "ranger",
                  min_n = tune(),
                  trees = tune() )

rf_params <- extract_parameter_set_dials(RF)


rf_grid <- rf_params |> 
  grid_latin_hypercube(size = 5)

wf_rf <- workflow() |>  
  add_model(RF) |> 
  add_recipe(rec)



wf_train <- wf_rf |>  
  tune_grid(resamples = folds,
            grid = rf_grid,
            control = keep_pred)

saveRDS(wf_train,"wf_rf_train.rds")

wf_train <- readRDS("wf_rf_train.rds")

best <- wf_train |>  
  select_best(metric = "roc_auc")

train_summary <- wf_train |> 
  collect_metrics(summarize = T)

p <- wf_train |> collect_predictions(parameters = best)


autoplot(wf_train, metric = "roc_auc")


wf_best <- finalize_workflow(wf_rf, best)


wf_best_fit <- wf_best |>  
  fit(train)

saveRDS(wf_best_fit,"wf_rf_best_fit.rds")


wf_best_fit <- readRDS("wf_rf_best_fit.rds")

#ramka danych predykcje

rf_pred <- predict(wf_best_fit, test)
rf_pred2 <- predict(wf_best_fit, test, type = "prob")

#ramka danych łączoa predykcje z rzeczywistymi danymi
rf_df <- bind_cols(rf_pred, "target" = test$y)
rf_df2 <- bind_cols(rf_pred2, "target" = test$y)

#confusion matrix
conf_rf <- conf_mat(rf_df, truth = "target", estimate = ".pred_class")

conf_rf |> 
  autoplot(type = "heatmap")


roc_auc(rf_df2,"target", ".pred_0")

forest_roc <- roc_curve(rf_df2,"target", ".pred_0")
forest_roc_plot <- ggplot()+
  geom_path(data = forest_roc, aes(x= 1-specificity, y=sensitivity))+
  theme_bw()
forest_roc_plot

accuracy(rf_df, target, .pred_class)
```

SVM

```{r echo=FALSE}

SVM <- svm_rbf(
  mode = "classification",
  engine = "kernlab",
  cost = tune(),
  rbf_sigma = tune(),
  margin = tune()
  )

rec2 <- recipe(y ~ ., data = train) |> 
  step_smote(y) |> 
  step_normalize(all_numeric())


svm_params <- extract_parameter_set_dials(SVM)


svm_grid <- svm_params |> 
  grid_latin_hypercube(size = 5)

wf_svm <- workflow() |>  
  add_model(SVM) |> 
  add_recipe(rec2)



cl <- makePSOCKcluster(detectCores(logical=FALSE)-1)
registerDoParallel(cl)


wf_train_svm <- wf_svm |>  
  tune_grid(resamples = folds,
            grid = svm_grid,
            control = keep_pred)

saveRDS(wf_train_svm, "wf_svm_train.rds")

wf_train_svm <- readRDS("wf_svm_train.rds")


best_svm <- wf_train_svm |>  
  select_best(metric = "roc_auc")


p_svm <- wf_train_svm |> collect_predictions(parameters = best_svm)

svm_train_summary <- wf_train_svm |> 
  collect_metrics(summarize = T)


autoplot(wf_train_svm)

#wf_train_svm |> show_best()


wf_best_svm <- finalize_workflow(wf_svm, best_svm)


wf_best_svm_fit <- wf_best_svm |>  
  fit(train)

stopCluster(cl)



saveRDS(wf_best_svm_fit, "wf_best_svm_fit.rds")


wf_best_svm_fit <- readRDS("wf_best_svm_fit.rds")


#ramka danych predykcje
svm_pred <- predict(wf_best_svm_fit, test)
svm_pred2 <- predict(wf_best_svm_fit, test, type = "prob")


#ramka danych łączoa predykcje z rzeczywistymi danymi
svm_df <- bind_cols(svm_pred, "target" = test$y)
svm_df2 <- bind_cols(svm_pred2, "target" = test$y)

#confusion matrix
conf_svm <- conf_mat(svm_df, truth = "target", estimate = ".pred_class")

conf_svm |> 
  autoplot(type = "heatmap")

#roc_auc
roc_auc(svm_df2,"target", ".pred_0")

#roc_curve
svm_roc <- roc_curve(svm_df2,"target", ".pred_0")
svm_roc_plot <- ggplot()+
  geom_path(data = svm_roc, aes(x= 1-specificity, y=sensitivity))+
  theme_bw()
svm_roc_plot

#accuracy
accuracy(svm_df, target, .pred_class)
```
